// SC is free software distributed under the MIT license
// config.h generated by configure
#pragma once

// Define to the one symbol short name of this package.
#define SC_NAME		"sc"
// Define to the version of this package.
#define SC_VERSION	0x7160
// Define to the version string of this package.
#define SC_VERSTRING	"v7.16-13-g2cb6acf"
// Define to the address where bug reports for this package should be sent.
#define SC_BUGREPORT	"Mike Sharov <msharov@users.sourceforge.net>"

#define DFLT_PAGER	"less"
#define LIBDIR		"/usr/local/lib"
#define DIESAVEPATH	"/tmp/" SC_NAME ".sav"
#define HISTORY_FILE	"/home/%s/.config/sc_history"
#define PLUGIN_DIR	LIBDIR "/plugins/"
#define USER_PLUGIN_DIR	"%s/.sc/plugins/"

#define UNUSED		__attribute__((unused))

#define HAVE_CURSES_H 1
