#
# The lang category Makefile.
#

# Hook up all lang ports
SUBDIR=	attoscript business-card-brainfuck cbmbasic f2c forth fpp \
	lazyk lcc mawk p2c pforth retro tinyscheme tradcpp ucpp yoctolisp

.include <bsd.subdir.mk>
